---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml

configMapGenerator:
  - name: alloy-config
    namespace: o11y
    files:
      - config.alloy
      - discovery.alloy
      - ingress.alloy
      - logs.alloy
      - metrics.alloy
      - outputs.alloy
    options:
      disableNameSuffixHash: true
