---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: o11y
spec:
  interval: 10m
  chart:
    spec:
      chart: fluent-bit
      version: '0.57.7'
      sourceRef:
        kind: HelmRepository
        name: fluent-bit-helm
        namespace: o11y
      interval: 10m
  values:
    hotReload:
      enabled: true

    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

    rbac:
      nodeAccess: true

    extraVolumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys

    extraVolumeMounts:
      - name: proc
        mountPath: /host/proc
        readOnly: true
      - name: sys
        mountPath: /host/sys
        readOnly: true

    config:
      service: |
        [SERVICE]
          Daemon        Off
          Flush         5
          Log_Level     info
          Parsers_File  /fluent-bit/etc/parsers.conf
          Parsers_File  /fluent-bit/etc/conf/custom_parsers.conf
          HTTP_Server   On
          HTTP_Listen   0.0.0.0
          HTTP_Port     2020
          Health_Check  On
          storage.metrics On
   
      inputs: |
        [INPUT]
            Name              tail
            Tag               kube.*
            Path              /var/log/containers/*.log
            multiline.parser  docker, cri
            DB                /var/log/flb_kube.db
            Mem_Buf_Limit     5MB
            Skip_Long_Lines   On
     
        [INPUT]
            Name              systemd
            Tag               host.*
            Systemd_Filter    _SYSTEMD_UNIT=kubelet.service
            Read_From_Tail    On
     
        [INPUT]
            Name              node_exporter_metrics
            Tag               node_metrics
            path.procfs       /host/proc
            path.sysfs        /host/sys
            Scrape_Interval   60

      filters: |
        [FILTER]
            Name                kubernetes
            Match               kube.*
            Merge_Log           On
            Keep_Log            Off
            K8S-Logging.Parser  On
            K8S-Logging.Exclude On
     
        [FILTER]
            Name    record_modifier
            Match   kube.*
            Record  cluster deep-thonk
     
        [FILTER]
            Name    record_modifier
            Match   node_metrics
            Record  cluster deep-thonk
     
      outputs: |
        [OUTPUT]
            Name     http
            Match    kube.*
            Host     victoria-logs-victoria-logs-single-server.o11y
            Port     9428
            URI      /insert/jsonline?_stream_fields=kubernetes_namespace_name,kubernetes_pod_name,kubernetes_container_name,cluster&_msg_field=log&_time_field=time
            Format   json_lines
            Compress gzip
     
        [OUTPUT]
            Name     http
            Match    host.*
            Host     victoria-logs-victoria-logs-single-server.o11y
            Port     9428
            URI      /insert/jsonline?_stream_fields=_SYSTEMD_UNIT,cluster&_msg_field=MESSAGE&_time_field=time
            Format   json_lines
            Compress gzip
     
        [OUTPUT]
            Name          prometheus_remote_write
            Match         node_metrics
            Host          victoria-metrics-victoria-metrics-single-server.o11y
            Port          8428
            Uri           /api/v1/write
            Add_Label     cluster deep-thonk
            Add_Label     job     node-exporter
